NOAA-OWP/hydrotools

README.md

- Context and content to root readme. Namely description, purpose, and brief install guide.
- Add gh-page deployable docmentation via sphinx
- Auto generated api documentation

Update repo documentation (WIP)

---

setup.py

Closes #4 
Adds the ability install the entire package.
- Namespace level setup tools file added.
- Add this to README

Add the ability to install the entire namespace level package

---

README.md

Add a link in readme to gh-pages
- add link in about (@hellkite500 please)
- [ x Any _change_ in functionality is tested

add link to gh-pages deployment. 

---

python/nwis_client/tests/test_nwis.py

Closes #23
- Fix typo in tests causing them to fail

Fix failing NWIS tests

---

docs/README.md
docs/evaluation_tools.gcp_client.gcp.rst
docs/evaluation_tools.gcp_client.rst
docs/evaluation_tools.gcp_client.utils.rst
docs/index.rst
docs/notes

Add README for how to create sphinx apidocs bindings and add bindings for the `gcp_client`.
Part of #27
- `sphinx-apidocs` how to README
- `sphinx-apidocs` bindings for `gcp_client`.
-
-
1.
-
-

Sphinx apidocs how to and added bindings for gcp client

---

README.md

This PR updates the README with notes about categorial datatypes.
- None
- None
- New section in README
1. N/A
- Closes #25 
- None

Update Readme with Categorical Notes

---

gitflow.md

Refresh gitflow documentation.

Update gitflow documentation

---

python/events/evaluation_tools/events/event_detection/decomposition.py
python/events/setup.py
python/events/tests/test_decomposition.py
setup.py

This PR cleans up some of the event detection code. It reduces the number of computations and separates the trend computation step from the detrend step more explicitly. This model will make more sense as we add more trend estimation techniques.
- `rolling_minimum` function is the method used to estimate the trend.
- Function parameters were removed where applicable.
- I found a bug in the method that tests event detection on noisy series. The scale and frequency of the noise was incorrect. For some reason I simulated ~1 fluctuation a day, but given the parameters, I clearly meant ~4 fluctuations a day. Also found better results by setting `start_radius` to 1 period over the expected noise frequency (`halflife`). This makes sense since the period of the simulated noise is actually …

Light Event Detection Refactor

---

docs/evaluation_tools.events.event_detection.decomposition.rst
docs/evaluation_tools.events.event_detection.rst
docs/index.rst
python/events/evaluation_tools/events/event_detection/decomposition.py

Add sphinx docs for `events.event_detection` for github pages.
- Autogenerated event detection docs
- None
- Corrected a spelling error
1. N/A
- None
- None

Add Event Detection to github pages

---

README.md

Move gh-pages documentation link up in readme so more findable
-
-
-
1.
-
-

Move gh-pages documentation link

---

MANIFEST.in
pyproject.toml
python/_restclient/pyproject.toml
python/_restclient/setup.py
python/events/pyproject.toml
python/events/setup.py
python/gcp_client/pyproject.toml
python/gcp_client/setup.py
python/metrics/pyproject.toml
python/metrics/setup.py
python/nwis_client/pyproject.toml
python/nwis_client/setup.py
setup.py

[PEP 517](https://www.python.org/dev/peps/pep-0517/#) adds build-system metafiles that tell the package building system (i.e. `pip`) what build tools are required to complete the build (i.e. `wheel`, `setuptools`). This PR introduces these files. See revisions below for other minor changes.
- Add files to comply with PEP 517 standards.
- Add myself as maintainer
- Small change in improper installation exception handling
- This is a WIP see Todos

Update namespace level setup.py to PEP 517 standards

---

python/_restclient/setup.py
python/nwis_client/setup.py

Update NWIS client and rest client package descriptions
- Update NWIS client and rest client package descriptions

Update NWIS client and rest client package descriptions

---

python/metrics/README.md

Adds explicit `README.md` to the `hydrotools.metrics` subpackage.

Add metrics README

---

python/events/README.md

Add `README.md` to events subpackage.

Add `README.md` to events subpackage

---

python/nwis_client/README.md

Add nwis_client README.md

---

.github/workflows/run_unit_tests.yml

Test against python 3.9 in gh actions unittests.
-
-
- Test against python 3.9 in gh actions
1.
-
-

Test against python 3.9 in gh actions unittests.

---

python/gcp_client/setup.py

This PR just incorporates additional information into the `gcp_client` setup script.

Add additional information to setup.py file for gcp_client

---

python/caches/CONTRIBUTING.md
python/caches/LICENSE
python/caches/MANIFEST.in
python/caches/README.md
python/caches/SECURITY.md
python/caches/TERMS.md
python/caches/setup.py

Pushing through without review. Updates `setup.py` metadata and adds OWP required files at the subpackage level.

Update caches with setup metadata and required files

---

python/events/README.md
python/events/setup.py

Minor update to documentation. Closes #36

Update event detection docs with tips

---

python/_restclient/setup.py
python/nwis_client/hydrotools/nwis_client/iv.py
python/nwis_client/setup.py

Adds long descriptions and classifiers to bring `_restclient` and `nwis_client` up to parity with other subpackages.

Add long description and classifiers to _restclient and nwis_client setup.py

---

python/gcp_client/README.md

Just a documentation update. Pushing through.

Update GCP Client README

---

.github/workflows/deploy-gh-pages.yml

This updates the package installation step for gh pages deployment.

Update gh pages deployment

---

python/events/README.md
python/metrics/README.md

This updates the README files for `events` and `metrics`.
Closes #108

Update events and metrics README.md

---

python/gcp_client/setup.cfg
python/nwis_client/setup.cfg
setup.cfg

This PR just updates the minimum required versions to guarantee compatibility across sub-packages for the upcoming 2.1.1 release.

Update minimum versions

---

README.md

Add SVI client to readme.
- Add SVI client to readme.
-
-

Add SVI to readme

---

.github/workflows/run_events.yml
.github/workflows/run_metrics.yml
.github/workflows/run_nwis_client.yml
.github/workflows/run_nwm_client.yml
.github/workflows/run_nwm_client_new.yml
.github/workflows/run_rest_client.yml
.github/workflows/run_svi_client.yml

This just adds a "workflow_dispatch:" trigger to individual workflows so they can be triggered manually.

Add manual trigger options to individual tests.

---

.github/workflows/run_events.yml
.github/workflows/run_metrics.yml
.github/workflows/run_nwis_client.yml
.github/workflows/run_nwm_client.yml
.github/workflows/run_nwm_client_new.yml
.github/workflows/run_rest_client.yml
.github/workflows/run_svi_client.yml

Fix indentation error with last PR.

New Workflow Manual Trigger Incorrectly Indented

---

.github/workflows/run_slow_unit_tests.yml

Add ability to run slow tests gh action manually

Add ability to run slow tests gh action manually

---

README.md

docs: fix agu presentation link

---

.github/workflows/run_slow_unit_tests.yml

ci: run slow unit tests on 3.11 & 3.12

---

.github/workflows/deploy-gh-pages.yml

Minor update to docs GH workflow to reflect new name of `nwm_client`.

update package name for docs workflow

---

docs/conf.py
docs/hydrotools.nwm_client.AzureFileCatalog.rst
docs/hydrotools.nwm_client.FileDownloader.rst
docs/hydrotools.nwm_client.GCPFileCatalog.rst
docs/hydrotools.nwm_client.HTTPFileCatalog.rst
docs/hydrotools.nwm_client.NWMClient.rst
docs/hydrotools.nwm_client.NWMClientDefaults.rst
docs/hydrotools.nwm_client.NWMFileCatalog.rst
docs/hydrotools.nwm_client.NWMFileClient.rst
docs/hydrotools.nwm_client.NWMFileProcessor.rst
docs/hydrotools.nwm_client.ParquetStore.rst
docs/hydrotools.nwm_client.UnitHandler.rst
docs/hydrotools.nwm_client.gcp.rst
docs/hydrotools.nwm_client.http.rst
docs/hydrotools.nwm_client.rst
docs/hydrotools.nwm_client.utils.rst

Updates nwm docs to reflect new source files.

Update nwm docs

---

python/svi_client/tests/test_integration.py

Weekly unit test failed yesterday. Same problem and fix addressed in #282

update pytest fixture from loop to event_loop in svi_client
