NOAA-OWP/hydrotools

- gitflow.md
The `gitflow.md` file initially prepared by @hellkite500 and edited by @jarq6c had a reference to the original `evaluation_tools` repository. This PR updates that reference to the new NOAA-OWP repository.
- Add reference to new repo.
- Remove reference to old repo.
- Documentation only.
1. No source changed. No tests needed.
- This is test PR that changes documentation.
- None
> Update repository reference in gitflow.md

- docs/Makefile
- docs/conf.py
- docs/evaluation_tools._restclient.rst
- docs/evaluation_tools.nwis_client.rst
- docs/index.rst
- docs/make.bat
- docs/notes
closes #8 
Adds documentation that can be deployed on a gh-pages branch using `sphinx`. For now, the files are written using restructured text, this is the default for sphinx, but this may change in the future for ease of use purposes.
Documentation can be built using `make html` when in the `/docs` dir. I marked in todos to add deps to reqs, but for now, this requires `sphinx` and `furo` (`furo` is the theme used by sphinx at the moment).
- API docs deployable on `gh-pages` branch
- In the future, we may want to move to markdown over restructured text for usability sake. 
- Deploy on `gh-pages` branch
- Figure out how to embed Jupyter notebooks in documentation (i.e. for examples)
-  Add deps to `requirements.txt`
> Add sphinx API docs for gh-pages

- python/nwis_client/evaluation_tools/nwis_client/iv.py
- python/nwis_client/setup.py
The client defaults to fetching only "active" status gage data.  By default, the NWIS rest API uses "all" as the default parameter.  When retrieving historical data, this causes a bit of a surprise when a gage comes back with no data.
Closes #10 
- Change default `site_status` from `active` to `all`
> change default site_status to all

- python/nwis_client/evaluation_tools/nwis_client/iv.py
- python/nwis_client/tests/test_nwis.py
Closes #11
- Warning is raised when no data is returned from nwis iv rest service.
- None
- If no data is returned by nwis, return an empty df
1. `test_get_throw_warning` added to test added code
> nwis_client: Return empty df and raise warning when no data returned from nwis

- README.md
- python/events/evaluation_tools/events/event_detection/decomposition.py
- python/events/requirements.txt
- python/events/setup.py
- python/events/tests/test_decomposition.py
- setup.py
This new subpackage is a more streamlined and simplified version of event detection using time series decomposition as it appears in Regina & Ogden, 2021 (under review).
- `evaluation_tools.events.event_detection.decomposition`
- Could be future home of additional event-based analysis methods
- None
- README.md has been updated to reflect the new subpackage.
- Advanced version to 1.2
1. Added single test for `list_events`. Due to the structure of the module, this tests all methods at least once.
2. This test fabricates a streamflow record with a single event and runs event detection to ensure a single event is detected.
- As per previous discussions, decomposition requires enough data to intelligently derive a baseflow trend. Time series should probably consist of at least 700 to 1000 …
> Add Event Detection Subpackage

- python/events/evaluation_tools/events/event_detection/decomposition.py
- python/events/setup.py
Tweaks `event_detection.decomposition` method. The original method cited (Regina & Ogden, 2020) used the maximum of the forward and backward rolling minimums. This doesn't have a huge effect on the number of events detected, but does tend to result in more slightly accurate start times because the maximum makes the trend "snap" to the input streamflow hydrograph.
The accuracy of event boundaries is still subject to overall signal and event characteristics.
- None
- None
- Uses maximum of forward and backward rolling minimums instead of mean.
- Updated type hints (`typing` did not like `pandas.offsets`)
- Version 0.2.1
1. Passes existing test.
- None
- None
> Minor Events Updates

- .github/workflows/run_unit_tests.yml
Closes  #17
- GH action that runs unit tests via `pytest` and `coverage`
- Using `coverage` to run the tests so in the future it will be easy to add a coverage badge.
- Create `coverage` badge and `gh-badge` branch.
> Add github action that runs unit tests

- .github/workflows/deploy-gh-pages.yml
Add a gh-action that automatically builds and deploys documentation to `gh-pages` when something is pushed to the main branch.
- gh-action for auto deploying gh-pages
- I am not 100% sure this will work, so it might be a WIP, just cant really test if it is going to work or not.
> gh-pages CI deployment

- .github/workflows/deploy-gh-pages.yml
Fix bug causing gh-page gh-action to fail. This is caused by `git push origin gh-pages` failing when nothing has been committed.
> Fix gh-pages deployment gh-action

- README.md
- python/metrics/evaluation_tools/metrics/metrics.py
- python/metrics/setup.py
- python/metrics/tests/test_metrics.py
Internal development revealed a logical error in `evaluation_tools.metrics.compute_contigency_table`. This fixes that and updates the unit test.
- None
- None
- Switch how false positives and false negatives are computed using `crosstab`.
1. The unit test that tests `compute_contingency_table` has been updated with corrected categorical test series.
- Closes #38 
- None
> Fix incorrect logic in compute_contingency_table

- python/gcp_client/setup.py
Move `gcp_client` version up in anticipation for `evaluation_tools` release.
-
-
-
1.
-
-
> Bump gcp_client version to 0.2.0

- python/events/evaluation_tools/events/event_detection/decomposition.py
- python/events/setup.py
- python/events/tests/test_decomposition.py
Introduces new optional parameter to filter events based on duration.
- New `minimum_event_duration` option for `evaluation_tools.events.event_detection.decomposition` methods
- None
- Additional optional parameters and documentation
1. Added `test_list_events_noise` method that simulates and tests a noisy signal
- This is a common post-processing step. These algorithms are prone to false positives
- None
> Add optional parameter to filter events using minimum duration

- python/events/evaluation_tools/events/event_detection/decomposition.py
- python/events/setup.py
- python/events/tests/test_decomposition.py
Phase shifts imparted by the constituent filters can cause event starts to miss the mark by a significant margin, especially on noisy data. Using this option can help fix that by shifting start times to a local minimum within some search window.
- New `start_radius` option
- None
- Added new option and logic to `mark_event_flows`
1. Verifies start is shifted to appropriate index for contrived noisy test event.
- Closes #37 
- None
> Add option to shift event start times to local minimum

- python/events/evaluation_tools/events/event_detection/decomposition.py
- python/events/setup.py
- python/events/tests/test_decomposition.py
- setup.py
Adds additional code to validate time series and test exceptions.
- Tests for non-duplicated monotonically increasing datetime index
- None
- `mark_event_flows` and `find_local_minimum` raise exceptions for invalid series
1. New tests verify exceptions are raised for bad series
- Lower level methods will also catch some of these, but these exceptions make them explicit
- None
> Raise exceptions for bad time series index in event detection

- CONTRIBUTING.md
- Include expected usage of `pyproject.toml` in `CONTRIBUTING.md`.
> Update contribution guide to reflect usage of pyproject.toml

- python/metrics/evaluation_tools/metrics/metrics.py
- python/metrics/setup.py
- python/metrics/tests/test_metrics.py
- setup.py
This add mean squared error and nash-suttcliffe efficiency to the `metrics` package. These tools are in a format compatible with `sklearn` and potentially other packages used to calibrate, test, and validate models. The methods can also be used alone to generate model evaluation statistics.
- `mean_squared_error` and `nash_suttcliffe_effiency` methods
- None
- Added two new methods and tests
1. Tests base functionality of each method, as well as additional RMSE, NSE long, and NNSE functionality.
- `numpy` *array_like* type hints require `numpy>=1.20`
- These methods see additional parameters in the future to reflect different statistical options.
- NSE could include a `bounded` parameter to offer an alternative method of "normalization"
- Skill scores like NSE follow the same general …
> Add MSE and NSE methods to metrics subpackage

- CONTRIBUTING.md
- setup.py
In the past it was required to manually update `setup.py` with requirements as well as their dir tree mapping (`slug-name: dir-location`). This PR simply changes the way things are handled in setup.py to support a building an overarching namespace package wheel in the future.
- Automatically determine requirements and namespace package dir tree mapping
> Update setuptools to automatically determine requirements and namespace package dir tree mapping

- docs/hydrotools._restclient._restclient.rst
- docs/hydrotools._restclient.rst
- docs/hydrotools._restclient.utilities.rst
- python/_restclient/hydrotools/_restclient/__init__.py
- python/_restclient/hydrotools/_restclient/_iterable_nonstring.py
- python/_restclient/hydrotools/_restclient/utilities.py
- python/_restclient/setup.py
- python/_restclient/tests/test_iterable_nonstring.py
- python/_restclient/tests/test_utilities.py
- `utilities` module under `_restclient` subpackage
- Immutable `Alias` class that accepts a key of any type and a value or collection of values that act as the alias to the key. To get key, use `.get(value) # returns key or None` or `[value] # throws ValueError if invalid value`.
- Immutable `AliasGroup` that supports a collection of `Alias` objects but treats them as a single `Alias`.
- `IterableNonStringLike` type for checking if object is an instance of an iterable type but not a string or byte. string and bytes are iterable in python3.
PR adds `hydrotools._restclient.utilities` which contains: Immutable `Alias` and `AliasGroup` classes. These classes serve to simplify library code where it is common to separate back-end implementation from the front-end api. Often this is applicable …
> _restclient utilities module: add Alias and AliasGroup classes

- python/nwis_client/setup.py
In reference to #67, there was an issue with unit tests failing because `nwis_client` was pulling it's dep on `_restclient` from github. I suspect this is a product of how dependency resolution is handled with `pip` > 21. 
- nwis_client now depends on _restclient from pypi
> nwis_client now depends on _restclient from pypi

- python/_restclient/README.md
Closes #62 
- `-restclient` `README.md` with example
1. Tested the example locally. Will not work until #67 is merged.
> Add _restclient README with example. Fulfill requirement in #62

- .github/workflows/run_unit_tests.yml
- python/_restclient/README.md
- python/_restclient/hydrotools/_restclient/__init__.py
- python/_restclient/hydrotools/_restclient/_iterable_nonstring.py
- python/_restclient/hydrotools/_restclient/_restclient.py
- python/_restclient/hydrotools/_restclient/_restclient_sigs.py
- python/_restclient/hydrotools/_restclient/async_client.py
- python/_restclient/hydrotools/_restclient/async_helpers.py
- python/_restclient/hydrotools/_restclient/urllib.py
- python/_restclient/hydrotools/_restclient/utilities.py
- python/_restclient/setup.py
- python/_restclient/tests/test_client.py
- python/_restclient/tests/test_restclient.py
- python/_restclient/tests/test_urllib.py
Main features:
- `RestClient`: a class which offers asynchronous performance via a convenient serial wrapper, sqlite database GET request caching, GET request backoff, batch GET requests, and flexible url argument encoding.
- `Url`: Treat urls like to `pathlib.Path`s. Supports appending paths with `/` and appending url query parameters with `+`.
- `ClientSession`: Extension of [`aiohttp_client_cache`](https://github.com/JWCook/aiohttp-client-cache) that adds exponential backoff.
- `Variadic`: Join list or tuple of objects on some delimiter. Useful when query parameters utilize a non-`key=value&key=value2` pattern.
- `Alias` and `AliasGroup`: Immutable utility classes that simplify common API library development patterns (i.e. separation of backend uris from front end interfaces). …
> Major refactor of RestClient

- CONTRIBUTING.md
- python/events/setup.py
- python/gcp_client/setup.py
- python/metrics/setup.py
- setup.py
Development deps like `pytest` have been moved to subpackage `setup.py`. To install development requirements for a specific subpackage you now do: `pip install -e hydrotools.subpackage[develop]`. The behavior for installing the entire subpackage has not changed, it is still `python setup.py develop`.
closes #79
-
-
- Development requirements moved from namespace package level to subpackage `setup.py` level. Now uses `pip install -e hydrotools.subpackage[develop]` semantics. Installation for namespace package in develop mode has not changed. 
- I did not include this in `_restclient` or `nwis_client`. This will be introduced for those subpackages in #86
> Move development deps concern from namespace to subpackage concern

- .github/workflows/run_unit_tests.yml
- python/nwis_client/setup.py
- python/nwis_client/tests/test_nwis.py
Add `_restclient` version requirement for `nwis_client`. Now requires `3.0.0`
The Run Unit Tests `gh-action` now installs `_restclient` explicitly prior to installing the namespace package. See below for context.
- This is a pre-release PR before the `restclient_transition` branch is merged into `main`
> Pre-release nwis_client require  _restclient 3.0.0 and gh-actions install _restclient explicitly

- setup.py
Bump minor namespace package version to 2.1.0
- `hydrotools` bumped to `2.1.0`.
> Bump minor namespace package version to 2.1.0

- .github/workflows/deploy-gh-pages.yml
Fixes the same issue 1c9f72384525bdeeb63e238d93bfa1d00e3fe767 (#91) resolved for unit test `gh-action` in `gh-pages` deployment.
> Explicitly install _restclient in develop mode for gh-pages deployment

- .github/workflows/deploy-gh-pages.yml
`pip install -e .` causing failure b.c. installing _restclient twice.
Related to #94
> fix gh-pages deployment. related to #94

- python/_restclient/setup.py
- python/nwis_client/setup.py
- setup.py
Add hydrotools github url to `_restclient` and `nwis_client` `setup.py` files plus update listed license.
> Add GitHub Url to setup.py

- python/events/hydrotools/events/event_detection/decomposition.py
- python/events/setup.py
Recent versions of pandas no longer allow the combination of a halflife with the recursive version of the EWMA. This changes the default to use a decaying adjustment factor.
- None
- None
- Use decaying adjustment factor.
1. Passes tests.
- Slight change to EWMA algorithm.
-
> events: Default to decaying adjustment factor

- python/gcp_client/hydrotools/gcp_client/gcp.py
- python/gcp_client/setup.py
- python/gcp_client/tests/test_gcp.py
This alters the behavior of `gcp_client` tool to return `nwm_feature_id` as `int` instead of string categories. This will simplify the interface and address a bug associated with trying to map crosswalk data across category types. Note: Keeping feature IDs as integers was originally suggested by @aaraney 
- Additional tests do limited (single site) validation of crosswalk application.
- any conversion of `nwm_feature_id` to str and/or category
- `nwm_feature_id` are now always integers
1. Test that feature id 6186112 is associated with usgs_site_code "01360640"
- No more reviewers :(
-
> gcp_client: Do not use string categories for NWM feature IDs

- python/gcp_client/hydrotools/gcp_client/gcp.py
- python/gcp_client/setup.py
Switch from using `multiprocessing.Pool` to `concurrent.futures.ProcessPoolExecutor`. This is partially a future-proof update to use the available generic interface for concurrency and offers a potential speed-up through the use of chunking.
- None
- None
- Switched from using `Pool` to `ProcessPoolExecutor`
1. Passed all existing tests.
- Closes #101 
- None
> GCP Client: Switch from mp to futures

- python/nwis_client/README.md
- python/nwis_client/setup.cfg
- python/nwis_client/src/hydrotools/nwis_client/iv.py
- python/nwis_client/tests/test_nwis.py
This is the first step in making `nwis_client` consistent with the HydroTools Canonical Format.
- new `value_time_label` option that lefts users set the label of the datetime column in returned dataframes from `get`
- None
- Option set at `__init__`. failing to set the option will raise a `UserWarning`
1. The basically functionality is tested by checking for the named column in the output
- This is step `, eventually this option will have different default behavior.
- None
> Add value_time_label option to nwis_client

- python/events/setup.cfg
- python/events/src/hydrotools/events/event_detection/decomposition.py
- python/events/tests/test_decomposition.py
Warn the user if event detection is called on a series with null values. Closes #51 
- UserWarning when calling detrend_series that contains null values
- None
- None
1. Warning is tested.
- Docs/README still recommends to fill null values.
- None
> Warn for Null values in series when calling event detection

- docs/conf.py
- docs/index.rst
Updates version and front page information in gh-pages.
> update name version and front page

- python/_restclient/setup.cfg
- python/_restclient/src/hydrotools/_restclient/_restclient.py
- python/_restclient/src/hydrotools/_restclient/async_helpers.py
- python/_restclient/tests/test_restclient.py
This is a resubmission of #100 with minor changes to the unit test added. 
Fixes #99. 
- If event loop is already running and `RestClient` is instantiated, try to `import nest_asyncio` and patch with `nest_asyncio.apply()`. Raise `ModuleNotFoundError` if `nest_asyncio` not installed.
1. Test added to verify `ModuleNotFoundError` is raised. If `nest_asyncio` is installed, test fails.
> Fix #99: "RuntimeError: This event loop is already running" in colab and notebook. Re-PR of #100

- python/nwis_client/setup.cfg
- python/nwis_client/src/hydrotools/nwis_client/iv.py
- python/nwis_client/tests/test_nwis.py
See #133 for the bug report. This PR resolves #133. Now, when a station does not have data, `nwis_client` returns a canonical dataframe with the correct data types to the user. Additionally, the user is warned that the request did not return data. 
fixes #133
Addenda: Updates empty dataframe method to return a non-canonical dataframe if specified by the user. Necessary for #117 
- canonical dataframe helper "private" method. This may be helpful for writing tests in the future/ asserting that dataframes comply with the standard. (see `_create_empty_canonical_df`)
-
- `nwis_client.get` returns a canonical dataframe with the correct data types in cases when no data is retrieved from nwis.
1. `test_get_returns_empty_canonical_dataframe` added. Uses mock to verify a canonical dataframe is …
> fix nwis_client bug causing KeyError when station does not return data -- Updated

- python/nwis_client/setup.cfg
- python/nwis_client/src/hydrotools/nwis_client/iv.py
- python/nwis_client/tests/test_nwis.py
See #133 for the bug report. This PR resolves #133. Now, when a station does not have data, `nwis_client` returns a canonical dataframe with the correct data types to the user. Additionally, the user is warned that the request did not return data. 
fixes #133
- canonical dataframe helper "private" method. This may be helpful for writing tests in the future/ asserting that dataframes comply with the standard. (see `_create_empty_canonical_df`)
-
- `nwis_client.get` returns a canonical dataframe with the correct data types in cases when no data is retrieved from nwis.
1. `test_get_returns_empty_canonical_dataframe` added. Uses mock to verify a canonical dataframe is returned.
> fix nwis_client bug causing KeyError when station does not return data

- python/nwm_client/tests/test_gcp.py
This update just limits the number of times tests for this subpackage make a request for NWM data. Slow tests would sometimes fail. I suspect the issue was lack was resources on the GH side. Previously, the tests ran all configurations, but that was excessive and did not increase our robustness since the same code was just tested repeatedly with similar circumstances. Specific fail-cases are already tested elsewhere.
> NWM Client: Limit number of get calls for testing

- python/nwm_client/setup.cfg
- python/nwm_client/src/hydrotools/nwm_client/_version.py
- python/nwm_client/src/hydrotools/nwm_client/gcp.py
See #180 for bug report. This PR lays the groundwork for two new releases of the `hydrotools.nwm_client`. The first release, `5.0.1-post1`, pins `h5netcdf<=0.13.0`. This was done to support users who would like to use the software but are dependent on a `h5netcdf<=0.13.0`. The second release is `5.0.2`, this pins `h5netcdf>=0.14.0`. `5.0.2` also includes a patch that fixes the `IndexError` propagating from `h5netcdf==0.14.0`.
fixes #180.
- if your application requires `h5netcdf<=0.13.0`, use `hydrotools.nwm_client==5.0.1-post1`
- otherwise, use `hydrotools.nwm_client>=5.0.2`
- Resolves `IndexError: invalid index to scalar variable.` present in `hydrotools.nwm_client<=5.0.1`
> Resolve Nwm client IndexError: invalid index to scalar variable. (#180)

- python/metrics/src/hydrotools/metrics/_validation.py
Some minor improvements to _validation.py that center around the usage of `np.asarray`. Using `np.asarray` over `np.array` can avoid unnecessary copies (ie, when the input is already an array).
When comparing the shapes, we don't need to hold all the arrays in memory.
> Improvements to validation checks

- python/nwm_client_new/setup.cfg
Pin importlib-metadata<=4.13.0. Remove when 3.7 support dropped.
Fixes #211.
- `nwm_client_new` dependency, `importlib-metadata` pinned to `<=4.13.0`
> Pin importlib-metadata version in nwm_client_new

- python/svi_client/setup.cfg
- python/svi_client/tests/test_integration.py
fixes #217
- Adds `pytest-aiohttp` development dependency to `svi_client`
1. Verified that this resolves locally `RuntimeError: There is no current event loop in thread 'MainThread'.` thrown in slow unit tests.
> Add pytest-aiohttp development  dep to svi_client

- .github/workflows/run_slow_unit_tests.yml
- .github/workflows/run_unit_tests.yml
`pip freeze` dependencies in github actions runners to improve debugging.
> Echo dependency versions in runners

- python/_restclient/pytest.ini
- python/_restclient/setup.cfg
bump `aiohttp` and `aiohttp_client_cache` version deps
See #103 for background as to why `aiohttp` was previously pinned. In short, the issues that led to pinning `aiohttp` have be resolved upstream.
`aiohttp_client_cache` >= 0.9.0 needed b.c. https://github.com/requests-cache/aiohttp-client-cache/issues/173
- `_restclient` depends on `aiohttp~=3.8` and `aiohttp_client_cache>=0.9.0`
> Bump _restclient's `aiohttp` and `aiohttp_client_cache` version deps

- python/nwis_client/src/hydrotools/nwis_client/iv.py
- python/nwis_client/tests/test_nwis.py
When using the IVDataService class to get usgs data, the rest client threads keep running after the main program has finished executing.
I managed to "fix" it by adding a context handler, but I'm not familiar enough with asyncio to make it work without the `with` syntax. 
```python
from hydrotools.nwis_client import IVDataService
service = IVDataService()
print("getting data")
usgs_data = service.get(sites="10154200", startDT="2001-01-01", endDT="2001-01-02")
print("done, exiting")
exit(1)
```
```console
getting data
done, exiting
^CException ignored in: <module 'threading' from '/usr/lib/python3.12/threading.py'>
Traceback (most recent call last):
File "/usr/lib/python3.12/threading.py", line 1622, in _shutdown
lock.acquire()
KeyboardInterrupt: 
^C
```
```python
from …
```
> Add nwis_client iv context handler

- .github/workflows/run_slow_unit_tests.yml
Simple fix for failing slow unit tests that removes testing for `caches` and `nwm_client_new` which no longer exist.
> Remove caches and and old nwm client from slow unit tests

- .github/workflows/run_slow_unit_tests.yml
> remove 3.8 and 3.9 testing from events

- python/_restclient/tests/test_restclient.py
Short and sweet. Minor correction to `test/test_restclient.py` Tagging @aaraney for sanity check.
Closes #281
> Correct pytest fixture

- python/_restclient/tests/test_client.py
- python/_restclient/tests/test_restclient.py
- python/_restclient/tests/test_urllib.py
Updates (yet again) the `event_loop` syntax in the _restclient tests.
https://pytest-asyncio.readthedocs.io/en/stable/how-to-guides/migrate_from_0_21.html
> Update `_restclient` asyncio testing syntax
